Feature/interlok 4453 update change char encoding service expressions
adaptris/interlok pull request #1724
Opened 2024-11-27 03:48 UTC by saurav-mukherjee-telus

## Motivation

Why am I doing this

## Modification

What did I change

## PR Checklist

- [x] been self-reviewed.
- [ ] Added javadocs for most classes and all non-trivial methods
- [ ] Added supporting annotations (like @XStreamAlias / @ComponentProfile)
- [ ] Added DefaultValue annotation when there is a default value (e.g. @DefaultValue('true'))
- [ ] Added validation annotation (@NotNull...) when required and add @Valid when nested class has some validation
- [ ] Checked that @NotNull and @NotBlank annotations have a meaningful message when appropriate.
- [ ] Checked that new 3rd party dependencies are appropriately licensed
- [ ] Added comments explaining the "why" and the intent of the code wherever it would not be obvious for an unfamiliar reader
- [ ] Added unit tests or modified existing tests to cover new code paths
- [ ] Tested new/updated components in the UI and at runtime in an Interlok instance
- [ ] Reviewed java class members so that missing annotations are added (InputFieldDefault/ComponentProfile etc)
- [ ] Checked that javadoc generation doesn't report errors
- [ ] Checked the display of the component in the UI
- [ ] Remove any config/license annotations
- [ ] Check the gradle build file to make sure the dependencies section is more explicit "implementation/api".

## Result

What's the end result for the user

## Testing

How can I test this if I'm reviewing this.

2024-11-27 05:57 UTC, sebastien-belin-adp commented on interlok-core/src/test/java/com/adaptris/core/services/ChangeCharEncodingServiceTest.java
> +    srv.setCharEncoding("%message{pn.processing.worker.transform.encoding-target}");
You don't/shouldn't need to use pn metadata here as Interlok is not PN.
But it doesn't matter.

2024-11-27 05:57 UTC, sebastien-belin-adp approved these changes

2024-11-27 06:03 UTC, sebastien-belin-adp requested changes
If you want to improve the coverage you could add another test with an empty char encoding value. That will test one more branch of the code.

2024-11-28 00:28 UTC, saurav-mukherjee-telus commented on interlok-core/src/test/java/com/adaptris/core/services/ChangeCharEncodingServiceTest.java
> +    srv.setCharEncoding("%message{pn.processing.worker.transform.encoding-target}");
Thanks @sebastien-belin-adp

2024-11-28 00:29 UTC, saurav-mukherjee-telus commented
> If you want to improve the coverage you could add another test with an empty char encoding value. That will test one more branch of the code.

Hi @sebastien-belin-adp  - Null character value test is in place now

2024-11-28 00:55 UTC, sebastien-belin-adp approved these changes
Thanks

2024-11-28 02:36 UTC, merged